NAME = libft.a
SOURCES = \
    ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c\
	ft_memset.c ft_bzero.c ft_memcpy.c ft_memmove.c ft_memcmp.c ft_strtrim.c\
    ft_strlcpy.c ft_strlcat.c ft_toupper.c ft_tolower.cft_strmapi.c \
	ft_memmove.c ft_calloc.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_substr.c ft_itoa.c \
    ft_strrchr.c ft_strncmp.c ft_memchr.c ft_atoi.c ft_strnstr.c ft_putnbr_fd.c ft_striteri.c  ft_split.c\

OBJECTS = $(SOURCES:.c=.o)

CC = cc
CFLAGS = -Wall -Wextra -Werror

all: $(NAME)

$(NAME): $(OBJECTS) libft.h
	ar -r $@ $?

clean:
	rm -f $(OBJECTS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY : clean re fclean all